### ISSUE TITLE
add script to generate the repository

### ISSUE THREAD

**Issue by ninrod** [d12frosted/elpa-mirror#1]
@d12frosted, I see you're using https://github.com/dochang/elpa-clone, but do you have some specific configuraiton for spacemacs? what specific steps do you employ to fetch this entire repo?

thanks in advance.

**Comment by d12frosted** [comment]
What do you mean? If you are interested in how I clone elpa package archives, then here is a quote from readme file.

> Maintained using [mirror-elpa](https://github.com/d12frosted/environment/tree/master/utils/mirror_elpa).

In short, I run [this script](https://github.com/d12frosted/environment/blob/master/utils/mirror_elpa/mirror_elpa) using `launchctl` (it's like `cron`, but for macOS). This script first verifies that `elpa-clone` exists somewhere (`ELPA_CLONE_PATH`). Then it resets `elpa-mirror` repository to latest `master`, then runs `emacs` in batch mode in order to clone desired elpa archive.

``` bash
function clone {
  log "Updating mirror for $2 ($1)"
  emacs -l "$ELPA_CLONE_PATH/elpa-clone.el" -nw --batch --eval="(elpa-clone \"$1\" \"$MIRROR_PATH/$2\")"
}
```

After that I just push.

This script is used for this repo and for Spacemacs elpa mirror repository.

**Comment by ninrod** [comment]
yes! that's what I meant: how to reproduce the clones. 

the suggestion is to keep the script that perform the clones here, in this repo.

**Comment by d12frosted** [comment]
Oh sorry, I saved the draft of the response to you and totally forgot about it.

It was there, once. But since it's not really tied to this mirror, I moved it to my `.environment/utils`. I should document it there. 👍

**Comment by d12frosted** [comment]
I've added some notes on script usage. Also, I did some improvements to make script less error-prone 💃 

Closing this issue as I am not going to move that script here anyways. But thanks for bringing it up!

**Comment by ninrod** [comment]
thanks @d12frosted. I fear the day you will stop doing this as this repo became my emacs lifeline, hehe.

**Comment by d12frosted** [comment]
@ninrod 

There's an [update](https://github.com/d12frosted/mirror-elpa). I thought that you might be interested.

**Comment by ninrod** [comment]
Hi @d12frosted! Thank you very much. 

Thanks to you I know have a fully customized script that is working very well __[here](https://github.com/ninrod/rsynced-melpa)__. Of interest is a rsync address I have found out in emacs-china for the elpa gnu servers. 

I'll take a look on your update, thanks.
