### ISSUE TITLE
update rate

### ISSUE THREAD

**Issue by ninrod** [d12frosted/elpa-mirror#2]
Hi @d12frosted! How what are your plans concerning mantaining this repo up to date? 

I only use your awesome repo for getting my packages and I'm itching to grab ivy 0.9. 

thanks in advance!

**Comment by d12frosted** [comment]
Hey @ninrod,

Thanks in the interest 😸 

Previously it was updated several times in a day. But then something broke and it stopped. I even didn't notice it haha. Thanks for letting me know. I'll fix my launch service to get to the work 😸

**Comment by ninrod** [comment]
awesome! There more I think about it, the more it makes sense for this to be a standard melpa feature you know? like, they could provide this kind of service where I could git clone their full package list as a git repo. Would be awesome.

**Comment by ninrod** [comment]
ref: https://github.com/melpa/melpa/issues/4706

**Comment by d12frosted** [comment]
Wow. That was really funny. First of all, it took some time to update all packages. Then it failed to commit changes, because gpg key I used to sign commits in this repo expired a month ago. And this is a reason why it stopped updating 😸 Sorry about that. I've updated my key and now updates will arrive with higher frequency 😸 Wait for several hours and update will arrive 😸 

Many thanks for noticing this repo being inactive 😸 

P. S. I have never noticed this issue, because I never really looked at logs. Haha. Now I can update my Emacs packages as well 😸 

P. P. S. Thanks for using my mirror 😜 

-------

> awesome! There more I think about it, the more it makes sense for this to be a standard melpa feature you know? like, they could provide this kind of service where I could git clone their full package list as a git repo. Would be awesome.

It sounds really good. No more desynchronisation. But on the other hand, it will be just MELPA and Stable MELPA. While you might want to have clone for GNU ELPA and org ELPA as well 😸

**Comment by d12frosted** [comment]
Closing this issue as initial problem is solved 😸 

Thanks again, @ninrod !

**Comment by ninrod** [comment]
AWESOME! thanks!

**Comment by purcell** [comment]
@d12frosted You're using our `rsync` service for this, right, rather than hammering the web server? (See [here](https://github.com/melpa/melpa/issues/4042#issuecomment-233171920) for details.)

**Comment by d12frosted** [comment]
@purcell Oops, I am hammering the web server using [elpa-clone](https://github.com/dochang/elpa-clone). Will switch to rsync ASAP.

P. S. didn't know about rsync back when I've created this mirror.

**Comment by purcell** [comment]
Thanks, I've filed a PR on `elpa-clone` to show its users how to use `rsync` instead for the repositories that support it: https://github.com/dochang/elpa-clone/pull/1

**Comment by ninrod** [comment]
thanks @purcell, I too didn't know that the rsync service existed. @d12frosted the rsync service seems to be even easier and way more efficient than the elpa-clone method.

**Comment by dochang** [comment]
@d12frosted @ninrod @purcell 

elpa-clone 0.0.5 supports rsync now!  Try it out:

```
(elpa-clone "elpa.gnu.org::elpa/" "/path/to/elpa")
(elpa-clone "rsync://melpa.org/packages/" "/path/to/elpa")
(elpa-clone "rsync://stable.melpa.org/packages/" "/path/to/elpa")
```

Please read README.md for details.

**Comment by d12frosted** [comment]
@dochang you are my hero! thanks a lot! will switch to new version and will use `rsync` for (S)MELPA. 

Note that changes to sync method won't be made in this repo, cause it's just a storage 😸

**Comment by d12frosted** [comment]
Ok, `rsync` works a way faster 😸 thanks again @dochang !

**Comment by purcell** [comment]
> Ok, rsync works a way faster 😸 

Yep, it's absolutely made for this task!

**Comment by d12frosted** [comment]
I know this issue is old. Initially the question was about update rate and wanted to share that now everything is done on CI and sync is run every 4 hours. 

Sync is running in [mirror-elpa][1] using this [GitHub workflow file][2].

  [1]: https://github.com/d12frosted/mirror-elpa/
  [2]: https://github.com/d12frosted/mirror-elpa/blob/master/.github/workflows/main.yaml
